modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory

modId="yummycake" #mandatory
version="2.0.0" #mandatory
displayName="Yummy Cake" #mandatory
logoFile="assets/yummycake/icon.png" #optional
authors="Command17" #optional
description='''
A small mod to add some cake.
'''

[[dependencies.yummycake]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.yummycake]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
